config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail = Cocktail.update(cocktail_params)
    redirect_to new_cocktail_dose_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

    def cocktail_params
      params.require(:cocktail).permit(:name, :photo)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    cocktail = Cocktail.find(params[:cocktail_id])
    ingredient = Ingredient.find(params[:dose][:ingredient_id])
    # ingredient = cocktail.doses.find(@dose.id)
    @dose.cocktail = cocktail
    @dose.ingredient = ingredient
    @dose.save
    redirect_to cocktails_path
  end

  private

    def dose_params
      params.require(:dose).permit(:description, :ingredient)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <h1>Modify the <%= @cocktail.name %></h1>

  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<div class="banner"></div>

<div class="container vh-100">
  <h1 class="text-center p-5">Our Cocktails <i class="fas fa-cocktail"></i></h1>
  <div class="cocktails_container">

    <!-- ADD A COCKTAIL CARD -->
    <%= link_to new_cocktail_path, class: "cocktail_card", id: "addACocktail"  do %>
        <h2>Add a cocktail</h2>
    <% end %>

    <!-- DISPLAY ALL COCKTAILS -->
    <% @cocktails.each do |cocktail| %>
      <div
      class="cocktail_card"
      style="background-image: url(<%= cl_image_path(cocktail.photo.key) if cocktail.photo.attached? %>)">
        <div>
          <%= link_to cocktail_path(cocktail) do %>
            <h2><%= cocktail.name %></h2>
          <% end %>
        </div>
        <div>
          <% cocktail.doses.each do |dose| %>
            <p> <%= dose.description %> <%= dose.ingredient.name %></p>
          <% end %>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Add Your Favorite Cocktail</h1>

  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <%= cl_image_tag @cocktail.photo.key, width: 300, height: 400 if @cocktail.photo.attached? %>
  <%= link_to 'Delete', cocktail_path(@cocktail), method: :delete%>
  <%= link_to 'Edit', edit_cocktail_path(@cocktail) %>
  <%= link_to 'Back', cocktails_path %>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h1>Add Your Favorite Cocktail</h1>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%# <%= f.input :ingredient, collection: Ingredient.order(:name) %>
    <%= f.association :ingredient %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%# GOOGLE FONTS %>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>